### ISSUE TITLE
Archiver fails on archived PV RTDSK0:MPA:02:POS_STATE_RBV

### ISSUE THREAD

**Issue by dcesar13** [slaclab/meme#3]
The meme.archive fails to retrieve the following PV at LCLS (RTDSK0:MPA:02:POS_STATE_RBV). 

Using the command line pvget as a monitor for this PV yields output like:
_$ RTDSK0:MPA:01:POS_STATE_RBV 2021-02-17 23:57:51.659  (0) RETRACTED_

The slac archiver gui is able to plot this PV.

Perhaps the problem is related to the fact that the output has two parts? A number/bool and text? I have checked the hist_service_get fails directly, as in:
_Value(id:NTComplexTable, Value(array([1613252106])))_

I do not know how to restructure the NTURI to get this PV, and the documentation on that is sparse.

**Comment by mattgibbs** [comment]
Hmmm.  This PV is working fine for me.  Here's my python terminal session on lcls-srv01:

```
>>> import meme
>>> meme.archive.get('RTDSK0:MPA:02:POS_STATE_RBV')
Orphaned server message 1 : not a channel request
{'secondsPastEpoch': array([1613252106, 1613655681, 1613655866, 1613660774]), 'values': array([0, 1, 0, 1], dtype=int32), 'nanoseconds': array([157600000, 536832000, 544300000, 757014000], dtype=int32), 'severity': array([0, 0, 0, 0], dtype=int32), 'status': array([0, 0, 0, 0], dtype=int32)}
```

Can you give me a little more info?  What are the arguments you provide to `meme.archive.get`?  Also, what machine are you running on?

**Comment by dcesar13** [comment]
Hmm,

This morning it also works for me, so I am closing the issue.  My best guess is:

We just added these PVs (they are the SXR CSR filters) to the Archiver last night. They only get archived when they cahnge (filter inserted/extracted). Perhaps my meme test was done before there were any values to read.

Thanks for testing this morning.
